### ISSUE TITLE
404 not handled on container stop

### ISSUE THREAD

**Issue by piontec** [piontec/docker-enforcer#12]
```
2017-05-12 11:10:19,818 - docker_enforcer - INFO - Container /condescending_hodgkin is detected to violate the rule "must have CPU limit". Stopping the container [Mode.Kill mode]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/containers/badd398df13bc30f2deec4519f20576409aef2bdba004a6e32ba730722fb5340/stop?t=10
```

**Comment by piontec** [comment]
Already resolved in 0.4.X
