### ISSUE TITLE
Exception thrown in a Thread is not handled in any on_error

### ISSUE THREAD

**Issue by piontec** [piontec/docker-enforcer#6]
THe following exception is not passed to any handler
```
2016-11-17 10:40:19,070 - docker_enforcer - INFO - Starting docker-enforcer v0.3.0 with docker socket 10.69.11.89:2375
 * Serving Flask app "docker_enforcer"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 508, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 543, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 589, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/eventloopscheduler.py", line 152, in run
    item.invoke()
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/linq/observable/subscribeon.py", line 34, in action
    d.disposable = ScheduledDisposable(scheduler, source.subscribe(observer))
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/rx/linq/observable/fromiterable.py", line 36, in action
    item = next(iterator)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/docker/client.py", line 245, in _stream_helper
    data = reader.read(1)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/piontec/.virtualenvs/docker-enforcer-dev/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by piontec** [comment]
should be OK in 0.4.1
