### ISSUE TITLE
Iterate over NoneType

### ISSUE THREAD

**Issue by piontec** [piontec/docker-enforcer#7]
```
2016-11-17 11:08:37,923 - docker_enforcer - DEBUG - Fetched data for container 666675983d598d59be68f1fc320efc3cf1bfbe992c351a5e090d97783ad5e77e
2016-11-17 11:08:37,923 - docker_enforcer - WARNING - An error occurred while trying to check running containers
2016-11-17 11:08:37,924 - docker_enforcer - ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/select.py", line 31, in on_next
    result = selector(value, count[0])
  File "/usr/local/lib/python3.5/site-packages/rx/internal/utils.py", line 29, in func_wrapped
    return cached[0](*args, **kw)
  File "/usr/local/lib/python3.5/site-packages/rx/internal/utils.py", line 22, in func1
    return func(arg1)
  File "/opt/docker_enforcer/docker_enforcer.py", line 55, in <lambda>
    .map(lambda container: judge.should_be_killed(container)) \
[2016-11-17 11:08:37,924] ERROR in killer: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/select.py", line 31, in on_next
    result = selector(value, count[0])
  File "/opt/docker_enforcer/dockerenforcer/killer.py", line 89, in should_be_killed
    if rule['rule'](container):
  File "/opt/docker_enforcer/rules/rules.py", line 13, in <lambda>
    b.startswith('/opt/gp2') for b in c.params['HostConfig']['Binds'])
TypeError: 'NoneType' object is not iterable
  File "/usr/local/lib/python3.5/site-packages/rx/internal/utils.py", line 29, in func_wrapped
    return cached[0](*args, **kw)
  File "/usr/local/lib/python3.5/site-packages/rx/internal/utils.py", line 22, in func1
    return func(arg1)
  File "/opt/docker_enforcer/docker_enforcer.py", line 55, in <lambda>
    .map(lambda container: judge.should_be_killed(container)) \
  File "/opt/docker_enforcer/dockerenforcer/killer.py", line 89, in should_be_killed
    if rule['rule'](container):
  File "/opt/docker_enforcer/rules/rules.py", line 13, in <lambda>
    b.startswith('/opt/gp2') for b in c.params['HostConfig']['Binds'])
TypeError: 'NoneType' object is not iterable
```

**Comment by piontec** [comment]
Bad rules file, not docker-enforcer bug
