### ISSUE TITLE
connection read timeout not handled

### ISSUE THREAD

**Issue by piontec** [piontec/docker-enforcer#9]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/local/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 395, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/eventloopscheduler.py", line 152, in run
    item.invoke()
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/subscribeon.py", line 34, in action
    d.disposable = ScheduledDisposable(scheduler, source.subscribe(observer))
  File "/usr/local/lib/python3.5/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/usr/local/lib/python3.5/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/fromiterable.py", line 40, in action
    observer.on_next(item)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/merge.py", line 128, in on_next
    observer.on_next(x)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/where.py", line 42, in on_next
    observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/select.py", line 36, in on_next
    observer.on_next(result)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/linq/observable/where.py", line 42, in on_next
    observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.5/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/opt/docker_enforcer/dockerenforcer/killer.py", line 111, in on_next
    self.__manager.kill_container(verdict.container)
  File "/opt/docker_enforcer/dockerenforcer/docker_helper.py", line 116, in kill_container
    self.__client.stop(container.params['Id'])
  File "/usr/local/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/docker/api/container.py", line 402, in stop
    timeout=(timeout + (self.timeout or 0)))
  File "/usr/local/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
```

**Comment by piontec** [comment]
should be OK in 0.4.1
